# Generated by Django 3.0.3 on 2020-09-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('PhoneNo', models.CharField(max_length=200)),
                ('Address', models.TextField(blank=True)),
                ('City', models.CharField(default='None', max_length=100)),
                ('State', models.CharField(default='None', max_length=100)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('picture', models.FileField(upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.TextField(blank=True)),
                ('City', models.CharField(default='None', max_length=100)),
                ('State', models.CharField(default='None', max_length=100)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('MobileNumber', models.CharField(max_length=200)),
                ('ShipmentWeight', models.DecimalField(decimal_places=2, default='00.00', max_digits=5)),
                ('Origin', models.TextField(blank=True)),
                ('Destination', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('1', 'OPEN'), ('2', 'CLOSED')], default='OPEN', max_length=100)),
                ('ShipmentDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deliveryperson', models.CharField(default='None', max_length=200)),
                ('Totalamount', models.DecimalField(decimal_places=2, default='00.00', max_digits=5)),
                ('picture', models.FileField(upload_to='static/mechit/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
