# Generated by Django 3.0.3 on 2020-09-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Uploadimage',
            field=models.ImageField(null=True, upload_to='static/mechit/images/'),
        ),
    ]
